#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh"
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/yifei/workspace/ns-allinone-3.26/bake/build/lib
 export PATH=$PATH:/home/yifei/workspace/ns-allinone-3.26/bake/build/bin
 export PYTHONPATH=$PYTHONPATH:/home/yifei/workspace/ns-allinone-3.26/bake:/home/yifei/workspace/ns-allinone-3.26/bake/build/lib:/home/yifei/workspace/ns-allinone-3.26/bake/build/lib/python2.7/dist-packages
